### ISSUE TITLE
ReviewDatabaseReadWriter saveToFile parameter

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#110]
Right now, you have it as Object reviews. Should the type of this be more specific? (ex. ReviewDatabase?) Or does it not matter.
For reference:

<img width="662" alt="Screen Shot 2022-12-06 at 10 23 11 AM" src="https://user-images.githubusercontent.com/46469244/205952700-f7e541dc-de4d-42f7-8a78-5315ff577297.png">
<img width="592" alt="Screen Shot 2022-12-06 at 10 23 18 AM" src="https://user-images.githubusercontent.com/46469244/205952711-88f57e49-caca-4d95-94fc-53951d2d3967.png">

**Comment by jkahn506** [comment]
That's a good point, I'll change it

**Comment by jkahn506** [comment]
Ok I fixed this.
