### ISSUE TITLE
Button to switch to sign up from login page

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#112]
Right now, if I accidentally click login when I don't have an account, can't switch to sign up page. Is it possible to add a sign up button on the login page? Or maybe this can be a next step for future updates

<img width="529" alt="Screen Shot 2022-12-06 at 11 35 43 AM" src="https://user-images.githubusercontent.com/46469244/205969753-2e0343c0-4821-404d-9ba5-51500cea1191.png">

**Comment by YadingF** [comment]
This will be on the future updates
