### ISSUE TITLE
SearchRecipeUI: ViewRecipeUI parameter missing (expected 1, have 0)

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#50]
Not sure why this error is popping up in the SearchRecipeUI.java.
The first image is what we have right now, and it says there needs to be 1 argument. According to ViewRecipeUI, it should be an AppController.
However, when I add the parameter, it says there should be 0 arguments.

(SearchRecipeUI.java)
<img width="958" alt="Screen Shot 2022-11-21 at 8 01 51 PM" src="https://user-images.githubusercontent.com/46469244/203189128-01766e76-6ed9-40c1-a683-c6c25e5dee86.png">
<img width="959" alt="Screen Shot 2022-11-21 at 8 02 31 PM" src="https://user-images.githubusercontent.com/46469244/203189132-93110120-49c9-4f12-bbe2-fab966516422.png">

(ViewRecipeUI.java)
<img width="566" alt="Screen Shot 2022-11-21 at 8 04 58 PM" src="https://user-images.githubusercontent.com/46469244/203189404-9a992222-6e22-4dbd-8ed3-5d9333792196.png">

**Comment by Hclover2003** [comment]
There is a similar error in the line below it

(SearchRecipeUI.java)
<img width="961" alt="Screen Shot 2022-11-21 at 8 08 55 PM" src="https://user-images.githubusercontent.com/46469244/203189823-d5a08c93-799c-4502-a1af-09057a974de9.png">

**Comment by Hclover2003** [comment]
should the three lines be deleted?
<img width="856" alt="Screen Shot 2022-11-21 at 8 16 31 PM" src="https://user-images.githubusercontent.com/46469244/203190642-b58b48b4-4c59-4772-afce-250b76ed26f8.png">

**Comment by Hclover2003** [comment]
Okay it works once those lines are deleted :))

**Comment by Brenden-Yiping-Wang** [comment]
When I pull from the main, I also met these problems. I delete most of them, because I tried to pass the appController in, rather than creating a new one in the ui. You can checkout my branch(view-one-recipe-3) or pull from it.
