### ISSUE TITLE
RecipeReadWriter, ReviewInteractor, UserList (getting all objects from a database)

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#71]
to get all objects from the database, right now,

- RecipeReadWriter.getRecipeList (get all recipes)
- ReviewInteractor.loadDatabase (get all reviews)
- userList.getAllUser (get all users

One is in Interactor, one is in ReadWriter (gateway), one is UserList. Which layer/class should this functionality be in? Does it matter if it's different for these different cases, or is this okay?

**Comment by Brenden-Yiping-Wang** [comment]
I believe that userList.getAllUser cannot get all the users if it has not stored in the database yet? In order to get all the stored users, we should use the gateway.

**Comment by Hclover2003** [comment]
Yes, can use readwriter and interactor to load data for all of these.
