### ISSUE TITLE
java.io.FileNotFoundException: user.sav

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#76]
I am trying to use the getAllUser function in UserRepoImpl
- (this is to get all the current users and save to a temp object before I run my test and add other users. That way, I can add these original users back into the database once I'm done my tests, leaving the database unchanged.)

However, this error is showing up:
<img width="768" alt="Screen Shot 2022-11-29 at 12 27 05 PM" src="https://user-images.githubusercontent.com/46469244/204600006-4a669f5f-2895-4fab-8ad7-3a66f041e3ec.png">

(SearchInteractorTest.java)
<img width="379" alt="Screen Shot 2022-11-29 at 12 27 46 PM" src="https://user-images.githubusercontent.com/46469244/204600098-9af461c2-e34f-49c5-ac13-e7bf4988ab45.png">

(UserRepoImpl.java)
<img width="598" alt="Screen Shot 2022-11-29 at 12 27 34 PM" src="https://user-images.githubusercontent.com/46469244/204600022-16c12a33-01c3-44ba-b96b-e4318ef56b97.png">

**Comment by Hclover2003** [comment]
For reference, users.sav does exist

<img width="403" alt="Screen Shot 2022-11-29 at 12 33 25 PM" src="https://user-images.githubusercontent.com/46469244/204601325-722b4929-0309-4189-9373-8c4411672486.png">

**Comment by YadingF** [comment]
Have you tried to (throws IOException), I tried my test which also used GetAllUser and I did not encounter this problem. Maybe try to see how Brenden did his interactor test~ It should be in Main.

**Comment by Hclover2003** [comment]
The error is gone now! :)) I didn't change anything though, maybe the users.sav was created afterwards?
