### ISSUE TITLE
read recipe returns same result (if use same input box)

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#92]
Steps:
1. Search Recipe: "apple pie", returns "apple pie" details. good
2. Close the apple pie details window
3. Type something else into search box: "sushi".

Problem: Still displays apple pie
https://user-images.githubusercontent.com/46469244/205377260-78641fe6-71f6-4a82-83b9-474a9e5a3e0e.mov

**Comment by Brenden-Yiping-Wang** [comment]
The problem has been solved by using ```label.setText```, rather than creating a new label
