### ISSUE TITLE
user's reviewed recipes: no reviewed recipe name

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#93]
<img width="192" alt="Screen Shot 2022-12-02 at 3 11 05 PM" src="https://user-images.githubusercontent.com/46469244/205377693-5edfb137-27fb-46c9-8fe2-9cdd4c05258a.png">

I reviewed the recipe "apple pie", but recipe name is not shown

**Comment by Allisonc369** [comment]
I fixed it yesterday
