### ISSUE TITLE
user's reviewed recipes: repeating same review

### ISSUE THREAD

**Issue by Hclover2003** [CSC207-2022F-UofT/course-project-collegecook#94]
I only made one review for one recipe (4/5), but everytime I click on "reviewed recipes" it duplicates (past display isn't erased)

<img width="192" alt="Screen Shot 2022-12-02 at 3 11 05 PM" src="https://user-images.githubusercontent.com/46469244/205378580-e89100f8-6148-470e-ad84-25a5cb5c10ed.png">

<img width="178" alt="Screen Shot 2022-12-02 at 3 11 29 PM" src="https://user-images.githubusercontent.com/46469244/205378567-55787f3a-9895-4db5-8391-893a0ae00056.png">
<img width="194" alt="Screen Shot 2022-12-02 at 3 18 20 PM" src="https://user-images.githubusercontent.com/46469244/205378635-0e616d8c-2a9d-4f08-9503-00fc714d221c.png">

**Comment by Allisonc369** [comment]
I fixed it yesterday.
